=== JoswinDsouza99/ChristUniversityLabWork/WebStack/xml/lnewsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ltn:schema xmlns:ltn="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/lnewsSchema" elementFormDefault="qualified">
<ltn:element name="news">
	<ltn:complexType>
		<ltn:sequence>
			<ltn:element name="Content" maxOccurs="unbounded">
				<ltn:complexType>
					<ltn:sequence>
						<ltn:element name="Category" type="ltn:string" />
						<ltn:element name="Headlines" type="ltn:string" />
						<ltn:element name="Date">
							<ltn:simpleType>
								<ltn:restriction base="ltn:date">
								<ltn:minInclusive value="2020-01-01"/>
                  				<ltn:maxInclusive value="2020-12-31"/>
								</ltn:restriction>
							</ltn:simpleType>
						</ltn:element>
					</ltn:sequence>
				</ltn:complexType>
			</ltn:element>
			<ltn:element name="User" maxOccurs="unbounded">
				<ltn:complexType>
					<ltn:sequence>
						<ltn:element name="U_id" type="ltn:int"/>
						<ltn:element name="Name" type="ltn:string"/>
						<ltn:element name="Email" type="ltn:string"/>
					</ltn:sequence>
				</ltn:complexType>
			</ltn:element>
		</ltn:sequence>
	</ltn:complexType>
</ltn:element>
</ltn:schema>

=== JoswinDsouza99/ChristUniversityLabWork/WebStack/xml/lnewsXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ltnStylesheet.xsl"?>
<news xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="lnewsSchema.xsd">
  <Content>
    <Category>Sports</Category>
    <Headlines>ICC Changes Test Championship Rules, India Go Down from First to Second Place</Headlines>
    <Article>The International Cricket Council (ICC) on Thursday announced changes to the ICC World Test Championship points 
    system that was amended due to the COVID-19 pandemic. According to the new system, Australia jump past India to claim the 
    top position. The Board approved a recommendation from the ICC Cricket Committee, headed by Anil Kumble, 
    to change the competition terms for the event to determine how series affected by the global pandemic are accounted 
    for on the points table.</Article>
    <Date>2020-11-20</Date>
  </Content>
  <Content>
    <Category>Sports</Category>
    <Headlines>Formula One Expects 24-race Calendar In Next Few Years</Headlines>
    <Article>The sport has pencilled in a record 23 for next year, dependent on developments in the COVID-19 pandemic 
    which forced organisers to rewrite this season`s schedule and limit races to Europe and the Middle East.
    Carey, who is handing over to former Ferrari team boss Stefano Domenicali in January while remaining as non-executive 
    chairman of the Liberty Media-owned sport, was speaking to investors.
    "We expect to move to a 24-race calendar in the next few years, and will probably rotate a few races so we will be able to 
    accommodate a few new partners," said the American.</Article>
    <Date>2020-11-20</Date>
  </Content>
  <Content>
    <Category>Business</Category>
    <Headlines>Switch to electric vehicles could 'end oil era': analysis</Headlines>
    <Article>Emerging markets switching from petrol and diesel engines to electric vehicles (EVs) could save 
    $250 billion annually and slash expected growth in global oil demand by as much as 70 percent, an industry analysis showed Friday.
    As more and more nations such as China and India look to grow their electic fleet, they are in turn reducing reliance on 
    imported oil, with EVs forecasted to soon be cheaper to make and run than their fossil-fuel-fired cousins.
    </Article>
    <Date>2020-11-20</Date>
  </Content>
  <User>
    <U_id>1</U_id>
    <Name>Jack</Name>
    <Email>jack@gmail.com</Email>
  </User>
    <User>
    <U_id>2</U_id>
    <Name>Jones</Name>
    <Email>jones@gmail.com</Email>
  </User>
    <User>
    <U_id>3</U_id>
    <Name>Jill</Name>
    <Email>jill@gmail.com</Email>
  </User>
    <User>
    <U_id>4</U_id>
    <Name>James</Name>
    <Email>james@gmail.com</Email>
  </User>
</news>
